{"type":"record","name":"CDef","namespace":"com.linkedin.cdef","fields":[
  {"name":"id","type":"long"},
  {"name":"c","type":{"type":"record","name":"C","fields":[
    {"name":"recs","type":{"type":"array","items":{"type":"record","name":"E","fields":[
      {"name":"ea","type":"int"},
      {"name":"eb","type":"string"}]}},"default":[{"ea":1,"eb":"x"}]},
    {"name":"byKey","type":{"type":"map","values":{"type":"record","name":"V","fields":[
      {"name":"va","type":"int"},
      {"name":"vb","type":"string"}]}},"default":{"k":{"va":2,"vb":"y"}}},
    {"name":"rec","type":{"type":"record","name":"RD","fields":[
      {"name":"ra","type":"int"},
      {"name":"rb","type":"string"}]},"default":{"ra":3,"rb":"z"}}]}}]}
