{"type": "record", "name": "F8Ns", "namespace": "com.linkedin.f8", "fields": [{"name": "a", "type": {"type": "record", "name": "Shared", "doc": "Shared record", "aliases": ["OldShared"], "x-shared": 1, "fields": [{"name": "x", "type": "int", "doc": "X value"}], "namespace": "com.linkedin.f8.one"}}, {"name": "b", "type": {"type": "record", "name": "Shared", "doc": "Shared record", "aliases": ["OldShared"], "x-shared": 1, "fields": [{"name": "x", "type": "int", "doc": "X value"}], "namespace": "com.linkedin.f8.two"}, "default": {"x": 1}}]}
