{"type":"record","name":"Nest","namespace":"com.linkedin.nest","fields":[
  {"name":"items","type":{"type":"array","items":{"type":"record","name":"Item","doc":"An item","fields":[
    {"name":"itemId","type":"long","doc":"Item id"},
    {"name":"itemExtra","type":["null","string"],"default":null},
    {"name":"itemName","type":"string"}]},"x-array-prop":"arr"}},
  {"name":"attrs","type":{"type":"map","values":{"type":"record","name":"Attr","fields":[
    {"name":"attrKey","type":"string"},
    {"name":"attrVal","type":"int"},
    {"name":"attrExtra","type":["null","string"],"default":null}]},"x-map-prop":"map"}},
  {"name":"mixed","type":{"type":"map","values":{"type":"array","items":{"type":"record","name":"Leaf","fields":[
    {"name":"leafExtra","type":["null","int"],"default":null},
    {"name":"leafId","type":"int"}]}}}}]}
