{"type":"record","name":"PageViewEvent","namespace":"com.linkedin.events","doc":"A page view","fields":[
  {"name":"eventId","type":"long","doc":"Event id"},
  {"name":"requestHeader","type":{"type":"record","name":"RequestHeader","doc":"Request header record","fields":[
    {"name":"pageKey","type":"string","doc":"Page key"},
    {"name":"path","type":["null","string"],"doc":"Request path","default":null}]},"doc":"The request header"},
  {"name":"tag","type":["null","string"],"default":null}]}
