package com.linkedin.coral.spark.containers;

import java.net.URI;


/**
 * This class aggregates all information required for registering a single UDF.
 *
 */
public class SparkUDFInfo {
  private String className;
  private String functionName;
  private URI artifactoryUrl;

  /**
   * @param className Class name of a Spark UDF
   *                  Example: com.linkedin.stdudfs.spark.daliudfs.EpochToDateFormatFunctionWrapper
   * @param functionName  Function name of the Spark UDF to be registered. The Spark-SQL generated by
   *                      CoralSpark.getExpandedSQL() will contain this name.
   *                      Example: epochToDateFormat
   * @param artifactoryUrl Artifactory Url to download all dependencies for this UDF.
   *                       Example: ivy://com.linkedin.standard-udfs-dali-udfs:standard-udfs-dali-udfs-spark:0.0.8
   *
   */
  public SparkUDFInfo(String className, String functionName, URI artifactoryUrl) {
    this.className = className;
    this.functionName = functionName;
    this.artifactoryUrl = artifactoryUrl;
  }

  /**
   * Get class name for the UDF implementation.
   *
   * @return  String  Class name of a Spark UDF
   *                  Example: com.linkedin.stdudfs.spark.daliudfs.EpochToDateFormatFunctionWrapper
   */
  public String getClassName() {
    return className;
  }

  /**
   * Get function name of the UDF, which will be needed while registering UDF.
   * Note: SQL retrieved from CoralSpark.getExpandedSQL() will contain this name.
   *
   * @return  String  Function name of the Spark UDF
   *                  Example: epochToDateFormat
   */
  public String getFunctionName() {
    return functionName;
  }

  /**
   * Artifactory Url to download all dependencies for this UDF.
   *
   * @return  URI  Artifactory Url to download all dependencies for this UDF
   *                  Example: ivy://com.linkedin.standard-udfs-dali-udfs:standard-udfs-dali-udfs-spark:0.0.8
   */
  public URI getArtifactoryUrl() {
    return artifactoryUrl;
  }

  @Override
  public String toString() {
    return "SparkUDFInfo{" + "className='" + className + '\'' + ", functionName='" + functionName + '\''
        + ", artifactoryUrl='" + artifactoryUrl + '\'' + '}';
  }
}
