{"type":"record","name":"@VIEW@","namespace":"fz.@VIEW@","fields":[
  {"name":"id","type":"long"},
  {"name":"c","type":{"type":"record","name":"C","namespace":"fz.@VIEW@.@VIEW@","fields":[
    {"name":"recs","type":{"type":"array","items":{"type":"record","name":"E","namespace":"fz.@VIEW@.@VIEW@.C","fields":[{"name":"ea","type":"int"},{"name":"eb","type":"string"}]}},"default":[{"ea":1,"eb":"x"}]},
    {"name":"byKey","type":{"type":"map","values":{"type":"record","name":"V","namespace":"fz.@VIEW@.@VIEW@.C","fields":[{"name":"va","type":"int"},{"name":"vb","type":"string"}]}},"default":{"k":{"va":2,"vb":"y"}}},
    {"name":"rec","type":{"type":"record","name":"RD","namespace":"fz.@VIEW@.@VIEW@.C","fields":[{"name":"ra","type":"int"},{"name":"rb","type":"string"}]},"default":{"ra":3,"rb":"z"}}]}}]}
