{"type": "record", "name": "@VIEW@", "namespace": "fz.@VIEW@", "fields": [{"name": "d", "type": {"type": "record", "name": "Shared", "namespace": "fz.@VIEW@.@VIEW@", "doc": "Shared record", "x-shared": 1, "fields": [{"name": "x", "type": ["int", "null"], "doc": "X value"}]}}, {"name": "arr", "type": {"type": "array", "items": "fz.@VIEW@.@VIEW@.Shared"}, "default": [{"x": 1}, {"x": 2}]}, {"name": "m", "type": {"type": "map", "values": "fz.@VIEW@.@VIEW@.Shared"}, "default": {"k": {"x": 3}, "j": {"x": 4}}}, {"name": "h", "type": {"type": "record", "name": "Holder", "namespace": "fz.@VIEW@.@VIEW@", "fields": [{"name": "s", "type": {"type": "record", "name": "Shared", "namespace": "fz.@VIEW@.@VIEW@.Holder", "doc": "Shared record", "x-shared": 1, "fields": [{"name": "x", "type": ["int", "null"], "doc": "X value"}]}}]}, "default": {"s": {"x": 5}}}]}
