{"type": "record", "name": "F8Ns", "namespace": "com.linkedin.f8", "fields": [{"name": "a", "type": {"type": "record", "name": "Shared", "namespace": "com.linkedin.f8.one", "doc": "Shared record", "x-shared": 1, "fields": [{"name": "x", "type": ["null", "int"], "doc": "X value"}], "aliases": ["OldShared"]}}, {"name": "b", "type": {"type": "record", "name": "Shared", "namespace": "com.linkedin.f8.two", "doc": "Shared record", "x-shared": 1, "fields": [{"name": "x", "type": ["int", "null"], "doc": "X value"}], "aliases": ["OldShared"]}, "default": {"x": 1}}]}
