{"type": "record", "name": "@VIEW@", "namespace": "fz.@VIEW@", "fields": [{"name": "a", "type": {"type": "record", "name": "Shared", "namespace": "fz.@VIEW@.@VIEW@-0", "doc": "Shared record", "x-shared": 1, "fields": [{"name": "x", "type": ["null", "int"], "doc": "X value"}]}}, {"name": "b", "type": {"type": "record", "name": "Shared", "namespace": "fz.@VIEW@.@VIEW@-1", "doc": "Shared record", "x-shared": 1, "fields": [{"name": "x", "type": ["int", "null"], "doc": "X value"}]}, "default": {"x": 1}}]}
